1.20211118-1~mtx1 release

diff --git a/debian/raspberrypi-kernel-mtx.postinst b/debian/raspberrypi-kernel-mtx.postinst
--- a/debian/raspberrypi-kernel-mtx.postinst
+++ b/debian/raspberrypi-kernel-mtx.postinst
@@ -23,7 +23,7 @@ is_pifour() {
   return $?
 }
 
-if [ "$(get_available_space)" -lt "49" ]; then
+if [ "$(get_available_space)" -lt "61" ]; then
   echo "You do not have enough space in /boot to install this package."
   SKIP_FILES=1
   if is_pifour; then
@@ -114,6 +114,11 @@ fi
 if [ -f /usr/share/rpikernelhack/bcm2710-rpi-cm3.dtb ]; then
   rm -f /boot/bcm2710-rpi-cm3.dtb
   dpkg-divert --package rpikernelhack --rename --remove /boot/bcm2710-rpi-cm3.dtb
+  sync
+fi
+if [ -f /usr/share/rpikernelhack/bcm2710-rpi-zero-2.dtb ]; then
+  rm -f /boot/bcm2710-rpi-zero-2.dtb
+  dpkg-divert --package rpikernelhack --rename --remove /boot/bcm2710-rpi-zero-2.dtb
   sync
 fi
 if [ -f /usr/share/rpikernelhack/bcm2711-rpi-4-b.dtb ]; then
@@ -1385,7 +1390,7 @@ if [ -d /usr/share/rpikernelhack ]; then
 fi
 
 touch /run/reboot-required
-if ! grep -qs "raspberrypi-kernel" /run/reboot-required.pkgs; then
-  echo "raspberrypi-kernel" >> /run/reboot-required.pkgs
+if ! grep -qs "raspberrypi-kernel-mtx" /run/reboot-required.pkgs; then
+  echo "raspberrypi-kernel-mtx" >> /run/reboot-required.pkgs
 fi
 #DEBHELPER#
