Signal reboot-required

diff --git a/debian/raspberrypi-bootloader.postinst b/debian/raspberrypi-bootloader.postinst
--- a/debian/raspberrypi-bootloader.postinst
+++ b/debian/raspberrypi-bootloader.postinst
@@ -134,4 +134,9 @@ fi
 if [ -d /usr/share/rpikernelhack ]; then
   rmdir --ignore-fail-on-non-empty /usr/share/rpikernelhack
 fi
+
+touch /run/reboot-required
+if ! grep -qs "raspberrypi-bootloader" /run/reboot-required.pkgs; then
+  echo "raspberrypi-bootloader" >> /run/reboot-required.pkgs
+fi
 #DEBHELPER#
diff --git a/debian/raspberrypi-kernel.postinst b/debian/raspberrypi-kernel.postinst
--- a/debian/raspberrypi-kernel.postinst
+++ b/debian/raspberrypi-kernel.postinst
@@ -1358,4 +1358,9 @@ fi
 if [ -d /usr/share/rpikernelhack ]; then
   rmdir --ignore-fail-on-non-empty /usr/share/rpikernelhack
 fi
+
+touch /run/reboot-required
+if ! grep -qs "raspberrypi-kernel" /run/reboot-required.pkgs; then
+  echo "raspberrypi-kernel" >> /run/reboot-required.pkgs
+fi
 #DEBHELPER#
